require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 2.7

RSpec/MultipleExpectations:
  Max: 6

RSpec/MultipleMemoizedHelpers:
  max: 6
